services:
  arangodb:
    image: arangodb:3.11
    container_name: mcp_arangodb_test
    environment:
      ARANGO_ROOT_PASSWORD: ${ARANGO_ROOT_PASSWORD:-changeme}
    ports:
      - "8529:8529"
    healthcheck:
      test: arangosh --server.username root --server.password "$ARANGO_ROOT_PASSWORD" --javascript.execute-string "require('@arangodb').db._version()" > /dev/null 2>&1 || exit 1
      interval: 5s
      timeout: 2s
      retries: 30
    restart: unless-stopped
    networks:
      - mcp-network

  mcp-arangodb-async:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: mcp_server
    environment:
      ARANGO_URL: http://arangodb:8529
      ARANGO_DB: ${ARANGO_DB:-_system}
      ARANGO_USERNAME: ${ARANGO_USERNAME:-root}
      ARANGO_PASSWORD: ${ARANGO_ROOT_PASSWORD:-changeme}
    depends_on:
      arangodb:
        condition: service_healthy
    stdin_open: true  # Enable stdin for stdio transport
    tty: true         # Allocate pseudo-TTY
    networks:
      - mcp-network
    restart: unless-stopped

networks:
  mcp-network:
    driver: bridge
